server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: test

  # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${db.username:root}
    password: ${db.password:Admin@123}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    open-in-view: false
    show-sql: true

  # i18n
  messages:
    basename: i18n/messages
    encoding: UTF-8

  # hashicorp/vault
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: TOKEN
      token: vault-root-token
      kv:
        enabled: true
        backend: secret

  # caching/redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  file:
    name: logs/access_log.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  logback:
    rollingpolicy:
      max-history: 7
      clean-history-on-start: true
  charset:
    console: UTF-8

dubbo:
  application:
    name: dubbo-provider-demo
    logger: slf4j
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.test.controller