server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: test

  # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${db.username:root}
    password: ${db.password:Admin@123}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    open-in-view: false
    show-sql: true

  # i18n
  messages:
    basename: i18n/messages
    encoding: UTF-8

  # hashicorp/vault
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: TOKEN
      token: vault-root-token
      kv:
        enabled: true
        backend: secret

    # Cloud stream - kafka
    stream:
      bindings:
        input: ## Consumer
          destination: demo-input-topic
          group: demo-group
        output: ## Producer
          destination: demo-output-topic
      kafka:
        binder:
          brokers: localhost:9092
          replication-factor: 1
          min-partition-count: 2
          auto-add-partitions: true
          auto-create-topics: true

  kafka:
    consumer:
      group-id: demo-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  # caching/redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  file:
    name: logs/access_log.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  logback:
    rollingpolicy:
      max-history: 7
      clean-history-on-start: true
  charset:
    console: UTF-8

dubbo:
  application:
    name: dubbo-provider-demo
    logger: slf4j
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181

# Resilience4j
## circuitbreaker
resilience4j.circuitbreaker:
  instances:
    circuitbreaker-conf:
      register-health-indicator: true
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 10
      permitted-number-of-calls-in-half-open-state: 10
      sliding-window-size: 100
## retry
resilience4j.retry:
  instances:
    retry-conf:
      max-attempts: 3
      wait-duration:
        seconds: 5
## rate limit
resilience4j.ratelimiter:
  instances:
    rateLimit-conf:
      limit-for-period: 10
      limit-refresh-period:
        seconds: 5
## bulkhead
resilience4j.bulkhead:
  instances:
    bulkhead-conf:
      max-concurrent-calls: 5
      max-wait-duration:
        seconds: 5
## time limit
resilience4j.timelimiter:
  instances:
    timeLimit-conf:
      timeout-duration:
        seconds: 3

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.test.controller